# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 5.0.0
version: "2"

services:
  app:
    image: mageinferno/magento2-nginx:1.11-0
    links:
      - phpfpm
      - db
    volumes_from:
      - appdata
    ports:
      - 8000:80

  appdata:
    image: tianon/true
    volumes:
      - /var/www/html
      - ~/.composer:/var/www/.composer

  phpfpm:
    image: mageinferno/magento2-php:7.0-fpm-0
    links:
      - db
    volumes_from:
      - appdata

  db:
    image: percona:5.7
    volumes_from:
      - dbdata
    ports:
      - 8001:3306
    env_file: .env

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  setup:
    image: mageinferno/magento2-php:7.0-fpm-0
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes_from:
      - appdata
    env_file: .env
